// frontend/react-todo/src/components/add-todo.tsx
import React from "react";

function AddTodo() {
  return (
    <div className="flex space-x-2 mb-4">
      <input
        type="text"
        className="input input-sm w-full bg-white border border-gray-400"
        placeholder="Add new todo"
      />
      <button className="btn btn-secondary btn-sm">Add</button>
    </div>
  );
}

export default AddTodo;

// frontend/svelte-todo/src/components/AddTodo.svelte
<script lang="ts">
  import todoStore from "../store/todoStore";

  const { addTodo } = todoStore();
  let newTodo: string = "";
</script>

<div class="flex items-center my-2">
  <input
    type="text"
    placeholder="Add todo"
    bind:value={newTodo}
    class="input input-sm input-bordered bg-white w-full"
  />
  <button
    class="btn btn-sm btn-primary ml-2"
    on:click={() => addTodo(newTodo).then(() => window.location.reload())}
    >Add</button
  >
</div>
