// frontend/svelte-todo/src/components/AddTodo.svelte
<script lang="ts">
  import todoStore from "../store/todoStore";

  const { addTodo } = todoStore();
  let newTodo: string = "";
</script>

<div class="flex items-center my-2">
  <input
    type="text"
    placeholder="Add todo"
    bind:value={newTodo}
    class="input input-sm input-bordered bg-white w-full"
  />
  <button
    class="btn btn-sm btn-primary ml-2"
    on:click={() => addTodo(newTodo).then(() => window.location.reload())}
    >Add</button
  >
</div>

// frontend/vue-todo/src/components/AddTodo.vue
<script lang="ts" setup>
import { store } from "../store/todoStore";
import { ref } from "vue";

const title = ref("");
</script>

<template>
  <div className="card card-compact bg-base-100 w-96 shadow-xl">
    <div className="card-body">
      <input
        type="text"
        placeholder="Add a new todo"
        className="input input-bordered"
        v-model="title"
      />
      <div className="card-actions  ">
        <button
          className="btn btn-primary w-full"
          @click="store.addTodo(title)"
        >
          Add
        </button>
      </div>
    </div>
  </div>
</template>
