// frontend/svelte-todo/src/components/Modal.svelte
<script lang="ts">
  import todoStore from "../store/todoStore";

  export let id: number;
  export let isEditing: boolean = false;
  export let toggleEditing: () => void;
  let newTodo: string;

  const { updateTodo } = todoStore();
</script>

<div>
  {#if isEditing}
    <div class="fixed top-0 left-0 w-full h-full bg-[rgba(0,0,0,.5)]">
      <div class="flex items-center justify-center w-full h-full">
        <div class="card bg-white p-6">
          <input
            type="text"
            bind:value={newTodo}
            placeholder="Edit todo"
            class="input input-sm input-bordered bg-white"
          />
          <button
            on:click={() =>
              updateTodo(id, newTodo).then(() => window.location.reload())}
            class="btn btn-sm btn-primary mt-2">Update</button
          >
          <button
            class="btn btn-sm btn-secondary mt-2"
            on:click={() => toggleEditing()}>CLOSE</button
          >
        </div>
      </div>
    </div>
  {/if}
</div>

// frontend/vue-todo/src/components/Modal.vue
<script setup lang="ts">
import { ref } from "vue";

const props = defineProps({
  id: Number,
  title: String,
  show: Boolean,
  close: Function,
});

const newTodo = ref("");

const onEdit = (e: any) => {
  e.preventDefault();
  newTodo.value = e.target.value;
};
const onSave = async () => {
  props.close;
  fetch(`http://localhost:3001/api/todos/${props.id}`, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title: newTodo.value,
    }),
  });
};
</script>

<template>
  <div
    :class="{
      hidden: !props.show,
      'fixed top-0 left-0 bg-[rgba(0,0,0,.1)] w-full h-full': props.show,
    }"
  >
    <div class="flex items-center h-full justify-center">
      <div class="card bg-white w-[400px] p-6 flex">
        <input
          type="text"
          placeholder="Edit todo"
          class="input input-md input-bordered bg-white mb-4"
          @change="onEdit"
        />
        <button class="btn btn-sm btn-primary mb-2" @click="onSave">
          Save
        </button>
        <button class="btn btn-sm btn-secondary" @click="props.close">
          Close
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped></style>
