// frontend/svelte-todo/src/components/Todo.svelte
<script lang="ts">
  import todoStore from "../store/todoStore";
  import Modal from "./Modal.svelte";

  const { todos, loading, error, deleteTodo } = todoStore();

  let isEditing: boolean = false;
  let id: number;

  function toggleEditing() {
    isEditing = !isEditing;
  }

  function toggleTodos(id: number) {
    const todo = $todos.find((todo) => todo.id === id);
    fetch(`http://localhost:3001/api/todos/${id}`, {
      method: "PATCH",
      body: JSON.stringify({
        completed: !todo?.completed,
      }),
      headers: {
        "Content-type": "application/json; charset=UTF-8",
      },
    });
  }
</script>

<div>
  {#if $loading}
    <p>Loading...</p>
  {:else if $error}
    <p>{error}</p>
  {:else}
    {#each $todos as todo (todo.id)}
      <div class="flex items-center justify-between my-2">
        <div class="flex space-x-1 w-full">
          <input
            type="checkbox"
            bind:checked={todo.completed}
            class="checkbox checkbox-primary"
            on:click={() => toggleTodos(todo.id)}
          />

          <p>{todo.title}</p>
        </div>
        <div class="flex space-x-2">
          <button
            on:click={() => {
              isEditing = true;
              id = todo.id;
            }}>EDIT</button
          >
          <button on:click={() => deleteTodo(todo.id)}>DELETE</button>
        </div>
      </div>
    {/each}
    <Modal {id} {isEditing} {toggleEditing} />
  {/if}
</div>

// frontend/vue-todo/src/components/Todo.vue
<script setup lang="ts">
import { ref, onMounted, onUpdated } from "vue";
import Modal from "./Modal.vue";

type Todo = {
  id: number;
  title: string;
  completed: boolean;
  createdAt: string;
  updatedAt: string;
};

const todos = ref<Todo[]>([]);
const edit = ref(false);

const getTodos = async () => {
  const res = await fetch("http://localhost:3001/api/todos");
  const data = await res.json();
  todos.value = data;
};

function onClose() {
  edit.value = false;
}

onMounted(() => {
  getTodos();
});

onUpdated(() => {
  getTodos();
});

const deleteTodo = (id: number) => {
  fetch(`http://localhost:3001/api/todos/${id}`, {
    method: "DELETE",
  });
};

const toggleTodo = (id: number) => {
  const check = todos.value.find((todo) => todo.id === id)?.completed;
  fetch(`http://localhost:3001/api/todos/${id}`, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      completed: !check,
    }),
  });
};
</script>

<template>
  <div>
    <ul>
      <li v-for="todo in todos" :key="todo.id">
        <Modal :id="todo.id" :show="edit" :close="onClose" />
        <div class="flex items-center justify-between my-2">
          <div class="flex items-center space-x-1">
            <input
              type="checkbox"
              :checked="todo.completed"
              class="checkbox-primary checkbox-sm checkbox"
              @click="toggleTodo(todo.id)"
            />
            <span :class="{ 'line-through': todo.completed }">{{
              todo.title
            }}</span>
          </div>
          <div class="space-x-2">
            <button class="" @click="edit = true">
              <i class="bx bx-edit"></i>
            </button>
            <button @click="deleteTodo(todo.id)">
              <i class="bx bx-x"></i>
            </button>
          </div>
        </div>
      </li>
    </ul>
  </div>
</template>

<style scoped></style>
