// frontend/react-todo/src/components/todo.tsx
import React, { useEffect, useState } from "react";
import { BiEditAlt, BiX } from "react-icons/bi";
import { useTodoStore } from "../store/todoStore";
import Modal from "./modal";

function Todo() {
  const [edit, setEdit] = useState(false);
  const { todos, toggleTodo, removeTodo, editTodo, load, newTodo } =
    useTodoStore();

  useEffect(() => {
    load();
  }, []);
  return (
    <React.Fragment>
      {todos.map((todo) => {
        return (
          <React.Fragment key={todo.id}>
            <Modal
              isOpen={edit}
              onClose={() => setEdit(false)}
              onSave={() => editTodo(todo.id, newTodo)}
              value={todo.title}
            />
            <div className="flex items-center justify-between py-2 px-2 border-b border-gray-500 text-sm">
              <div className="flex items-center">
                <input
                  type="checkbox"
                  checked={todo.completed}
                  className="checkbox checkbox-secondary mr-2"
                  onChange={() => toggleTodo(todo.id)}
                />
                <h1
                  className={
                    todo.completed ? "line-through text-black" : "text-black"
                  }
                >
                  {todo.title}
                </h1>
              </div>
              <div className="space-x-2 flex items-center">
                <button
                  className="text-red-500 hover:text-blue-500 transition-colors duration-300"
                  onClick={() => setEdit((prev) => !prev)}
                >
                  <BiEditAlt />
                </button>
                <button
                  className="text-red-500 hover:text-blue-500 transition-colors duration-300"
                  onClick={() => removeTodo(todo.id)}
                >
                  <BiX />
                </button>
              </div>
            </div>
          </React.Fragment>
        );
      })}
    </React.Fragment>
  );
}

export default Todo;

// frontend/vue-todo/src/components/Todo.vue
<script setup lang="ts">
import { ref, onMounted, onUpdated } from "vue";
import Modal from "./Modal.vue";

type Todo = {
  id: number;
  title: string;
  completed: boolean;
  createdAt: string;
  updatedAt: string;
};

const todos = ref<Todo[]>([]);
const edit = ref(false);

const getTodos = async () => {
  const res = await fetch("http://localhost:3001/api/todos");
  const data = await res.json();
  todos.value = data;
};

function onClose() {
  edit.value = false;
}

onMounted(() => {
  getTodos();
});

onUpdated(() => {
  getTodos();
});

const deleteTodo = (id: number) => {
  fetch(`http://localhost:3001/api/todos/${id}`, {
    method: "DELETE",
  });
};

const toggleTodo = (id: number) => {
  const check = todos.value.find((todo) => todo.id === id)?.completed;
  fetch(`http://localhost:3001/api/todos/${id}`, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      completed: !check,
    }),
  });
};
</script>

<template>
  <div>
    <ul>
      <li v-for="todo in todos" :key="todo.id">
        <Modal :id="todo.id" :show="edit" :close="onClose" />
        <div class="flex items-center justify-between my-2">
          <div class="flex items-center space-x-1">
            <input
              type="checkbox"
              :checked="todo.completed"
              class="checkbox-primary checkbox-sm checkbox"
              @click="toggleTodo(todo.id)"
            />
            <span :class="{ 'line-through': todo.completed }">{{
              todo.title
            }}</span>
          </div>
          <div class="space-x-2">
            <button class="" @click="edit = true">
              <i class="bx bx-edit"></i>
            </button>
            <button @click="deleteTodo(todo.id)">
              <i class="bx bx-x"></i>
            </button>
          </div>
        </div>
      </li>
    </ul>
  </div>
</template>

<style scoped></style>
