// frontend/react-todo/src/components/todos.tsx
import React, { useEffect, useRef, useState } from "react";
import { useTodos } from "../hooks/useTodos";
import { cn } from "../lib/utils";
import { Pencil, Trash } from "lucide-react";

function Todos() {
  const { todos, fetchTodos, toggleTodo, updateTodo, deleteTodo } = useTodos();
  const [input, setInput] = useState("");
  useEffect(() => {
    fetchTodos();
  }, []);
  return (
    <div className="space-y-2">
      <AddTodos />
      <div className="shadow-xl card bg-base-100 w-96">
        <div className="card-body">
          <h1 className="text-lg font-bold">Todos</h1>
          {todos.map((todo) => (
            <div key={todo.id} className="flex items-center justify-between">
              <p className={cn(todo.completed && "line-through")}>
                {todo.title}
              </p>
              <div className="flex space-x-2">
                <input
                  type="checkbox"
                  checked={todo.completed}
                  onChange={() => toggleTodo(todo.id, todo.completed)}
                />

                <Pencil
                  size={14}
                  className="cursor-pointer"
                  onClick={() =>
                    (
                      document.getElementById(
                        `my_modal_${todo.id}`
                      ) as HTMLDialogElement
                    ).showModal()
                  }
                />
                <Trash
                  size={14}
                  className="cursor-pointer"
                  onClick={() => deleteTodo(todo.id)}
                />
                <dialog id={`my_modal_${todo.id}`} className="modal">
                  <div className="modal-box">
                    <h3 className="text-lg font-bold">Edit Todo</h3>
                    <input
                      type="text"
                      placeholder="Edit Todo"
                      className="w-full mt-4 mb-2 input input-bordered"
                      onChange={(e) => setInput(e.currentTarget.value)}
                    />

                    <div className="modal-action">
                      <form method="dialog" className="space-x-2">
                        {/* if there is a button in form, it will close the modal */}
                        <button
                          className="btn btn-primary"
                          onClick={() => {
                            updateTodo(todo.id, input, todo.completed);
                          }}
                        >
                          Save
                        </button>
                        <button className="btn">Close</button>
                      </form>
                    </div>
                  </div>
                </dialog>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function AddTodos() {
  const { addTodo } = useTodos();
  const inputRef = useRef<HTMLInputElement>(null);
  return (
    <div className="shadow-xl card bg-base-100 w-96">
      <div className="card-body">
        <input
          type="text"
          placeholder="Add Todos"
          className="input input-bordered"
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              addTodo(e.currentTarget.value);
              e.currentTarget.value = "";
            }
          }}
          ref={inputRef}
        />
        <div className="card-actions ">
          <button
            className="w-full btn btn-primary"
            onClick={() => {
              if (!inputRef.current) return;

              addTodo(inputRef.current.value);
            }}
          >
            Add
          </button>
        </div>
      </div>
    </div>
  );
}

export default Todos;

// frontend/vue-todo/src/components/Todos.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { store } from "../store/todoStore";
import { Pencil, Trash } from "lucide-vue-next";
const input = ref("");
const dialogRefs = ref<Record<number, HTMLDialogElement | null>>({});

onMounted(() => {
  store.fetchTodos();
});
</script>

<template>
  <div class="card card-compact bg-base-100 w-96 shadow-xl">
    <div class="card-body">
      <h1 class="text-lg font-bold">Todos</h1>
      <div class="divide-y divide-gray-200">
        <div class="py-2">
          <ul>
            <li v-for="todo in store.todos" :key="todo.id">
              <div class="flex justify-between">
                <div>
                  <input
                    type="checkbox"
                    class="form-checkbox h-5 w-5 text-primary-600"
                    :checked="todo.completed"
                    @change="store.toggleTodo(todo.id, todo.completed)"
                  />
                  <span
                    :class="{ 'line-through': todo.completed }"
                    class="ml-2"
                  >
                    {{ todo.title }}
                  </span>
                </div>
                <div class="flex space-x-2">
                  <Pencil
                    @click="dialogRefs[todo.id]?.showModal()"
                    :size="14"
                    class="cursor-pointer"
                  />
                  <Trash
                    @click="store.deleteTodo(todo.id)"
                    :size="14"
                    class="cursor-pointer"
                  />
                </div>

                <dialog
                  :id="`my_modal_${todo.id}`"
                  class="modal"
                  :ref="el => dialogRefs[todo.id] = el as HTMLDialogElement"
                >
                  <div class="modal-box">
                    <h3 class="text-lg font-bold">Edit Todo</h3>
                    <input
                      type="text"
                      placeholder="Edit Todo"
                      class="w-full mt-4 mb-2 input input-bordered"
                      v-model="input"
                    />
                    <div class="modal-action">
                      <form method="dialog" class="space-x-2">
                        <button
                          class="btn btn-primary"
                          @click="store.editTodo(todo.id, input)"
                        >
                          Save
                        </button>
                        <button class="btn">Close</button>
                      </form>
                    </div>
                  </div>
                </dialog>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>
